apiVersion: apps/v1
kind: Deployment
metadata:
  name: defiflow-frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: defiflow-frontend
  template:
    metadata:
      labels:
        app: defiflow-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: nextjs
          # 这是一个占位符，GitHub Actions 会修改它
          image: ghcr.io/niroyue1/defiflow-frontend:sha-5d29d32504475bee07a9c3b5008a85ba4179d1eb
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: GEMINI_API_KEY  # 这是容器内看到的环境变量名
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets  # K8s 里 Secret 的名字 (第一步创建的)
                  key: GEMINI_API_KEY   # Secret 里的键名
---
apiVersion: v1
kind: Service
metadata:
  name: defiflow-frontend-svc
  namespace: default
spec:
  selector:
    app: defiflow-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000