apiVersion: apps/v1
kind: Deployment
metadata:
  name: defiflow-frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: defiflow-frontend
  template:
    metadata:
      labels:
        app: defiflow-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: nextjs
          image: ghcr.io/defiflow/flowstate-frontend:sha-8d914fd1b25fd425fb30ffd9d6447aaf462a4912
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: GEMINI_API_KEY
            - name: ALCHEMY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: ALCHEMY_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: defiflow-frontend-svc
  namespace: default
spec:
  selector:
    app: defiflow-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000